spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  application:
    name: shiro
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?characterEncoding=UTF-8
    username: root
    password: 123


server:
  servlet:
    context-path: /shiro
  port: 8080
mybatis:
  type-aliases-package: com.baizhi.springboot_jsp_shiro.entity
  mapper-locations: classpath:com/baizhi/mapper/*.xml